load("@rules_rs//rs/private:rust_crate.bzl", "rust_crate")
load(":cargo_crate_identity_info_test.bzl", "cargo_crate_identity_info_tests")

_IDENTITY = 'cargo:["registry","sparse+https://index.crates.io/","metadata-crate","1.2.3"]'

rust_crate(
    name = "metadata_crate",
    aliases = {},
    allow_build_script_to_detect_nonhermetic_paths = False,
    binaries = {"tool": "main.rs"},
    build_deps = [],
    build_script = "build.rs",
    build_script_data = [],
    build_script_env = {},
    build_script_env_files = [],
    build_script_tags = [],
    build_script_toolchains = [],
    build_script_tools = [],
    conditional_crate_features = {},
    crate_features = [],
    crate_identity = _IDENTITY,
    crate_name = "metadata_crate",
    crate_root = "lib.rs",
    data = [],
    edition = "2021",
    has_lib = True,
    is_proc_macro = False,
    link_deps = [],
    links = None,
    purl = "pkg:cargo/metadata-crate@1.2.3",
    rustc_flags = [],
    tags = [],
    target_compatible_with = [],
    triples = [],
    use_legacy_rules_rust_platforms = False,
    version = "1.2.3",
    deps = [],
)

rust_crate(
    name = "proc_metadata",
    aliases = {},
    allow_build_script_to_detect_nonhermetic_paths = False,
    binaries = {},
    build_deps = [],
    build_script = None,
    build_script_data = [],
    build_script_env = {},
    build_script_env_files = [],
    build_script_tags = [],
    build_script_toolchains = [],
    build_script_tools = [],
    conditional_crate_features = {},
    crate_features = [],
    crate_identity = _IDENTITY,
    crate_name = "proc_metadata",
    crate_root = "proc.rs",
    data = [],
    edition = "2021",
    has_lib = True,
    is_proc_macro = True,
    link_deps = [],
    links = None,
    purl = "pkg:cargo/metadata-crate@1.2.3",
    rustc_flags = [],
    tags = [],
    target_compatible_with = [],
    triples = [],
    use_legacy_rules_rust_platforms = False,
    version = "1.2.3",
    deps = [],
)

cargo_crate_identity_info_tests()
