load("@rules_rs//rs:rust_library.bzl", "rust_library")
load("@workspace_lints//:defs.bzl", "lint_config")

rust_library(
    name = "package_lints",
    srcs = ["src/lib.rs"],
    crate_name = "package_lints",
    edition = "2024",
    lint_config = lint_config(),
    visibility = ["//:__pkg__"],
)
