use std::collections::{BTreeMap, BTreeSet};
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, ExitCode};

struct Options {
    rustc: PathBuf,
    output: PathBuf,
    triples: Vec<String>,
}

fn parse_options() -> Result<Options, String> {
    let mut args = env::args().skip(1);
    let mut rustc = None;
    let mut output = None;
    let mut triples = Vec::new();

    while let Some(arg) = args.next() {
        let value = args
            .next()
            .ok_or_else(|| format!("missing value for {arg}"))?;
        match arg.as_str() {
            "--rustc" => rustc = Some(PathBuf::from(value)),
            "--output" => output = Some(PathBuf::from(value)),
            "--triple" => triples.push(value),
            _ => return Err(format!("unknown argument: {arg}")),
        }
    }

    if triples.is_empty() {
        return Err("at least one --triple is required".to_owned());
    }
    triples.sort();
    if triples.windows(2).any(|pair| pair[0] == pair[1]) {
        return Err("duplicate target triple".to_owned());
    }

    Ok(Options {
        rustc: rustc.ok_or("--rustc is required")?,
        output: output.ok_or("--output is required")?,
        triples,
    })
}

fn run_rustc(rustc: &Path, args: &[&str]) -> Result<String, String> {
    let output = Command::new(rustc)
        .args(args)
        .output()
        .map_err(|error| format!("failed to execute {}: {error}", rustc.display()))?;
    if !output.status.success() {
        return Err(format!(
            "{} {} failed:\n{}",
            rustc.display(),
            args.join(" "),
            String::from_utf8_lossy(&output.stderr)
        ));
    }
    String::from_utf8(output.stdout)
        .map_err(|error| format!("rustc emitted non-UTF-8 output: {error}"))
}

fn starlark_string(value: &str) -> String {
    let mut result = String::from("\"");
    for ch in value.chars() {
        match ch {
            '\\' => result.push_str("\\\\"),
            '"' => result.push_str("\\\""),
            '\n' => result.push_str("\\n"),
            '\r' => result.push_str("\\r"),
            '\t' => result.push_str("\\t"),
            _ => result.push(ch),
        }
    }
    result.push('"');
    result
}

fn header(version: &str) -> String {
    format!(
        "\"\"\"Generated Cargo cfg data. Do not edit by hand.\n\nGenerated by //rs/private:generated_cfg_target_data.\nOracle: {version}\n\"\"\"\n\n"
    )
}

fn render(version: &str, cfgs: &BTreeMap<String, Vec<String>>) -> String {
    let atoms: BTreeSet<&str> = cfgs
        .values()
        .flat_map(|values| values.iter().map(String::as_str))
        .collect();
    let atoms: Vec<&str> = atoms.into_iter().collect();
    let atom_ids: BTreeMap<&str, usize> = atoms
        .iter()
        .enumerate()
        .map(|(index, atom)| (*atom, index))
        .collect();

    let mut output = header(version);
    output.push_str("CFG_ATOMS = [\n");
    for atom in &atoms {
        output.push_str("    ");
        output.push_str(&starlark_string(atom));
        output.push_str(",\n");
    }
    output.push_str("]\n\nCFG_ATOM_IDS_BY_TRIPLE = {\n");
    for (triple, values) in cfgs {
        output.push_str("    ");
        output.push_str(&starlark_string(triple));
        output.push_str(": [");
        for (index, value) in values.iter().enumerate() {
            if index != 0 {
                output.push_str(", ");
            }
            output.push_str(&atom_ids[value.as_str()].to_string());
        }
        output.push_str("],\n");
    }
    output.push_str("}\n");
    output
}

fn write(path: &Path, content: &str) -> Result<(), String> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .map_err(|error| format!("failed to create {}: {error}", parent.display()))?;
    }
    fs::write(path, content).map_err(|error| format!("failed to write {}: {error}", path.display()))
}

fn run() -> Result<(), String> {
    let options = parse_options()?;
    let verbose_version = run_rustc(&options.rustc, &["--version", "--verbose"])?;
    let version = verbose_version
        .lines()
        .next()
        .ok_or("rustc --version --verbose returned no output")?;

    let mut cfgs = BTreeMap::new();
    for triple in options.triples {
        let output = run_rustc(
            &options.rustc,
            &["--print=cfg", &format!("--target={triple}")],
        )?;
        let values: BTreeSet<String> = output
            .lines()
            .filter(|line| !line.is_empty())
            .map(str::to_owned)
            .collect();
        cfgs.insert(triple, values.into_iter().collect());
    }

    write(&options.output, &render(version, &cfgs))?;
    Ok(())
}

fn main() -> ExitCode {
    match run() {
        Ok(()) => ExitCode::SUCCESS,
        Err(error) => {
            eprintln!("{error}");
            ExitCode::FAILURE
        }
    }
}
